name: Java CI with Gradle

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Execute executeBDD tests
      run: ./gradlew executeBDDTests --info -Pusername=$USER_NAME -Ppassword=$PASSWORD -Pbaseurl=https://trello.com
